# Generated by Django 2.2.11 on 2020-03-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='voites',
            new_name='votes',
        ),
    ]
